default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: discourse
  password: 9527serverpwd
  host: localhost
development:
  <<: *default
  database: academia_dev_tmp2
test:
  <<: *default
  database: academia_test
production:
  <<: *default
  database: academia_dev_tmp2
