default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  host: localhost
development:
  <<: *default
  database: a_dev_1
test:
  <<: *default
  database: a_test_1
production:
  <<: *default
  database: a_dev_1
