default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  host: localhost
  database: academia_dev
test:
  <<: *default
  host: localhost
  database: academia_test
production:
  <<: *default
  database: academia_production
  host: <%=ENV ['PG_HOST'] %>
  username: <%=ENV ['PG_USERNAME'] %>
  password: <%=ENV ['PG_PASSWORD'] %>

