default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: discourse
  password: 9527serverpwd
  host: localhost
development:
  <<: *default
  database: academia_dev_dev
test:
  <<: *default
  database: academia_test_dev
production: <%= ENV["RAILS_DATABASE_URL"] %>
